# Generated by Django 4.2.7 on 2023-11-30 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tx', models.CharField(max_length=128)),
                ('log_type', models.CharField(choices=[('SET_DATA', 'Set Data'), ('LICENSE_REGISTERED', 'License Registered'), ('LICENSE_REVOKED', 'License Revoked'), ('REQUIREMENT_REGISTERED', 'Requirement Registered'), ('REQUIREMENT_REVOKED', 'Requirement Revoked'), ('EVIDENCE_REGISTERED', 'Evidence Registered'), ('EVIDENCE_REVOKED', 'Evidence Revoked')], max_length=32)),
                ('block_number', models.IntegerField()),
                ('contract_address', models.CharField(max_length=128)),
                ('timestamp', models.IntegerField()),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('license_name', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_id', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_name', models.CharField(blank=True, default='', max_length=1024)),
                ('start_date', models.IntegerField(default=0)),
                ('end_date', models.IntegerField(default=0)),
                ('additional_data', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_id', models.CharField(blank=True, default='', max_length=1024)),
                ('evidence_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_name', models.CharField(blank=True, default='', max_length=1024)),
                ('key', models.CharField(blank=True, default='', max_length=1024)),
                ('value', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_id', models.CharField(blank=True, default='', max_length=1024)),
                ('evidence_id', models.CharField(blank=True, default='', max_length=1024)),
                ('key', models.CharField(blank=True, default='', max_length=1024)),
                ('value', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='LatestSyncedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_block_kv', models.IntegerField(default=-1)),
                ('last_synced_block_license', models.IntegerField(default=-1)),
                ('last_synced_block_requirement', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('license_name', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_id', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_name', models.CharField(blank=True, default='', max_length=1024)),
                ('start_date', models.IntegerField(default=0)),
                ('end_date', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=128)),
                ('tx', models.CharField(max_length=128)),
                ('license_address', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseProduct',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('license_address', models.CharField(max_length=128, unique=True)),
                ('requirement_address', models.CharField(max_length=128)),
                ('kv_address', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRequirements',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_name', models.CharField(blank=True, default='', max_length=1024)),
                ('state', models.CharField(max_length=128)),
                ('tx', models.CharField(max_length=128)),
                ('license_address', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
