# Generated by Django 4.2.7 on 2023-12-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestsyncedblock',
            name='last_synced_block_kv',
        ),
        migrations.RemoveField(
            model_name='latestsyncedblock',
            name='last_synced_block_license',
        ),
        migrations.RemoveField(
            model_name='latestsyncedblock',
            name='last_synced_block_requirement',
        ),
        migrations.AddField(
            model_name='latestsyncedblock',
            name='last_synced_block_number',
            field=models.IntegerField(default=0),
        ),
    ]
