# Generated by Django 4.2.7 on 2023-12-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='license',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='licenserequirements',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='licenserequirements',
            name='license_address',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncer.licenseproduct'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncer.licenseproduct'),
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncer.licenseproduct'),
        ),
        migrations.AddField(
            model_name='licenserequirements',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncer.licenseproduct'),
        ),
    ]
