# Generated by Django 4.0.2 on 2023-12-18 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0003_evidence_tx'),
    ]

    operations = [
        migrations.CreateModel(
            name='KV',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=1024)),
                ('value', models.CharField(blank=True, default='', max_length=1024)),
                ('timestamp', models.IntegerField(default=0)),
                ('tx', models.CharField(default='', max_length=128)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncer.licenseproduct')),
            ],
        ),
    ]
