# Generated by Django 4.2.7 on 2023-12-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0003_evidence_additional_data_license_additional_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='contract_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='evidence',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='contract_address',
            field=models.CharField(default='', max_length=1288),
        ),
        migrations.AddField(
            model_name='license',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='licenserequirements',
            name='contract_address',
            field=models.CharField(default='', max_length=1288),
        ),
        migrations.AddField(
            model_name='licenserequirements',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
