# Generated by Django 4.0.2 on 2023-12-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0007_eventlog_additional_data_kv'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_kv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_kv', to='syncer.kv'),
        ),
    ]
