# Generated by Django 4.0.2 on 2023-12-19 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0008_evidence_evidence_kv'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='requirement_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncer.licenserequirements'),
        ),
        migrations.AddField(
            model_name='licenserequirements',
            name='license_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncer.license'),
        ),
    ]
