# Generated by Django 4.0.2 on 2024-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0009_evidence_requirement_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='log_type',
            field=models.CharField(choices=[('SET_DATA', 'Set Data'), ('LICENSE_REGISTERED', 'License Registered'), ('LICENSE_UPDATED', 'License Updated'), ('LICENSE_REVOKED', 'License Revoked'), ('REQUIREMENT_REGISTERED', 'Requirement Registered'), ('REQUIREMENT_REVOKED', 'Requirement Revoked'), ('EVIDENCE_REGISTERED', 'Evidence Registered'), ('EVIDENCE_REVOKED', 'Evidence Revoked')], max_length=32),
        ),
    ]
