# Generated by Django 4.0.2 on 2025-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0011_license_additional_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='end_date',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='start_date',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kv',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='license',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='licenserequirements',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
