# Generated by Django 4.2.7 on 2023-11-07 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('request_type', models.CharField(choices=[('REGISTER', 'Register'), ('UPDATE_DURATION', 'Update Duration'), ('REMOVE_ENGINEER', 'Remove Engineer'), ('ADD_ENGINEER', 'Add Engineer')], default='REGISTER', max_length=16)),
                ('state', models.IntegerField(choices=[(0, 'Draft')], default=0)),
                ('callback_url', models.CharField(blank=True, max_length=256)),
                ('data', models.CharField(default='', max_length=2048)),
            ],
        ),
    ]
