# Generated by Django 4.2.7 on 2023-12-04 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('request_type', models.CharField(choices=[('REGISTER', 'Register'), ('REVOKE', 'Revoke'), ('UPDATE_DURATION', 'Update Duration'), ('ADD_EMPLOYEE', 'Add Employee'), ('REMOVE_EMPLOYEE', 'Remove Employee'), ('ADD_REQUIREMENT', 'Add Requirement'), ('REMOVE_REQUIREMENT', 'Remove Requirement')], default='REGISTER', max_length=20)),
                ('state', models.IntegerField(choices=[(0, 'Draft')], default=0)),
                ('callback_url', models.CharField(blank=True, max_length=256)),
                ('data', models.CharField(default='', max_length=2048)),
            ],
        ),
    ]
