# Generated by Django 4.2.7 on 2023-11-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_registration_issuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseproduct',
            name='license_address',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
