# Generated by Django 4.2.7 on 2023-11-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_registration_issuer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSyncedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_block_kv', models.IntegerField(default=-1)),
                ('last_synced_block_license', models.IntegerField(default=-1)),
                ('last_synced_block_requirement', models.IntegerField(default=-1)),
            ],
        ),
    ]
