# Generated by Django 4.2.7 on 2023-11-09 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_registration_issuer', '0002_latestsyncedblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tx', models.CharField(max_length=128)),
                ('log_type', models.CharField(choices=[('SET_DATA', 'Set Data'), ('LICENSE_REGISTERED', 'License Registered'), ('LICENSE_REVOKED', 'License Revoked'), ('REQUIREMENT_REGISTERED', 'Requirement Registered'), ('REQUIREMENT_REVOKED', 'Requirement Revoked'), ('EVIDENCE_REVOKED', 'Evidence Registered')], max_length=32)),
                ('block_number', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('license_name', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_id', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_name', models.CharField(blank=True, default='', max_length=1024)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('additional_data', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_id', models.CharField(blank=True, default='', max_length=1024)),
                ('evidence_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_name', models.CharField(blank=True, default='', max_length=1024)),
                ('key', models.CharField(blank=True, default='', max_length=1024)),
                ('value', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
