# Generated by Django 4.2.7 on 2023-11-23 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_registration_issuer', '0002_alter_licenseproduct_license_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('license_name', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_id', models.CharField(blank=True, default='', max_length=1024)),
                ('owner_name', models.CharField(blank=True, default='', max_length=1024)),
                ('start_date', models.IntegerField(default=0)),
                ('end_date', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=128)),
                ('tx', models.CharField(max_length=128)),
            ],
        ),
    ]
