# Generated by Django 4.2.7 on 2023-11-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_registration_issuer', '0003_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='contract_address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
