# Generated by Django 4.2.7 on 2023-11-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_registration_issuer', '0004_license_contract_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='contract_address',
            new_name='license_address',
        ),
    ]
