# Generated by Django 4.2.7 on 2023-11-27 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_registration_issuer', '0005_rename_contract_address_license_license_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_id', models.CharField(blank=True, default='', max_length=1024)),
                ('evidence_id', models.CharField(blank=True, default='', max_length=1024)),
                ('key', models.CharField(blank=True, default='', max_length=1024)),
                ('value', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRequirements',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_id', models.CharField(blank=True, default='', max_length=1024)),
                ('requirement_name', models.CharField(blank=True, default='', max_length=1024)),
                ('state', models.CharField(max_length=128)),
                ('tx', models.CharField(max_length=128)),
                ('license_address', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
